
typedef enum {
  /* Autogenerated IANA CBOR Content-Formats (Source: https://www.iana.org/assignments/cbor-simple-values/cbor-simple-values.xhtml#simple) */
  // False; Ref: [RFC8949]
  CBOR_SIMPLE_VALUE_FALSE = 20,
  // True; Ref: [RFC8949]
  CBOR_SIMPLE_VALUE_TRUE = 21,
  // Null; Ref: [RFC8949]
  CBOR_SIMPLE_VALUE_NULL = 22,
  // Undefined; Ref: [RFC8949]
  CBOR_SIMPLE_VALUE_UNDEFINED = 23
} cbor_simple_value_t;
