
#define COAP_CODE(CLASS, CODE) ((CLASS<<5)|(CODE))
typedef enum {
} coap_code_t;

typedef enum {
} coap_option_number_t;

typedef enum {
  /* Autogenerated IANA CoAP Content-Formats (Source: https://www.iana.org/assignments/core-parameters/core-parameters.xhtml#content-formats) */
  /* text/plain; charset=utf-8; Ref: [RFC2046][RFC3676][RFC5147] */
  TEXT_PLAIN_UTF_8 = 0,
  /* application/cose; cose-type="cose-encrypt0"; Ref: [RFC9052] */
  APPLICATION_COSE_ENCRYPT0 = 16,
  /* application/cose; cose-type="cose-mac0"; Ref: [RFC9052] */
  APPLICATION_COSE_MAC0 = 17,
  /* application/cose; cose-type="cose-sign1"; Ref: [RFC9052] */
  APPLICATION_COSE_SIGN1 = 18,
  /* application/ace+cbor; Ref: [RFC9200] */
  APPLICATION_ACE_CBOR = 19,
  /* image/gif; Ref: [https://www.w3.org/Graphics/GIF/spec-gif89a.txt] */
  IMAGE_GIF = 21,
  /* image/jpeg; Ref: [ISO/IEC 10918-5] */
  IMAGE_JPEG = 22,
  /* image/png; Ref: [RFC2083] */
  IMAGE_PNG = 23,
  /* application/link-format; Ref: [RFC6690] */
  APPLICATION_LINK_FORMAT = 40,
  /* application/xml; Ref: [RFC3023] */
  APPLICATION_XML = 41,
  /* application/octet-stream; Ref: [RFC2045][RFC2046] */
  APPLICATION_OCTET_STREAM = 42,
  /* application/exi; Ref: ["Efficient XML Interchange (EXI) Format 1.0 (Second Edition)", February 2014] */
  APPLICATION_EXI = 47,
  /* application/json; Ref: [RFC8259] */
  APPLICATION_JSON = 50,
  /* application/json-patch+json; Ref: [RFC6902] */
  APPLICATION_JSON_PATCH_JSON = 51,
  /* application/merge-patch+json; Ref: [RFC7396] */
  APPLICATION_MERGE_PATCH_JSON = 52,
  /* application/cbor; Ref: [RFC8949] */
  APPLICATION_CBOR = 60,
  /* application/cwt; Ref: [RFC8392] */
  APPLICATION_CWT = 61,
  /* application/multipart-core; Ref: [RFC8710] */
  APPLICATION_MULTIPART_CORE = 62,
  /* application/cbor-seq; Ref: [RFC8742] */
  APPLICATION_CBOR_SEQ = 63,
  /* application/edhoc+cbor-seq; Ref: [RFC-ietf-lake-edhoc-22] */
  APPLICATION_EDHOC_CBOR_SEQ = 64,
  /* application/cid-edhoc+cbor-seq; Ref: [RFC-ietf-lake-edhoc-22] */
  APPLICATION_CID_EDHOC_CBOR_SEQ = 65,
  /* application/cose; cose-type="cose-encrypt"; Ref: [RFC9052] */
  APPLICATION_COSE_ENCRYPT = 96,
  /* application/cose; cose-type="cose-mac"; Ref: [RFC9052] */
  APPLICATION_COSE_MAC = 97,
  /* application/cose; cose-type="cose-sign"; Ref: [RFC9052] */
  APPLICATION_COSE_SIGN = 98,
  /* application/cose-key; Ref: [RFC9052] */
  APPLICATION_COSE_KEY = 101,
  /* application/cose-key-set; Ref: [RFC9052] */
  APPLICATION_COSE_KEY_SET = 102,
  /* application/senml+json; Ref: [RFC8428] */
  APPLICATION_SENML_JSON = 110,
  /* application/sensml+json; Ref: [RFC8428] */
  APPLICATION_SENSML_JSON = 111,
  /* application/senml+cbor; Ref: [RFC8428] */
  APPLICATION_SENML_CBOR = 112,
  /* application/sensml+cbor; Ref: [RFC8428] */
  APPLICATION_SENSML_CBOR = 113,
  /* application/senml-exi; Ref: [RFC8428] */
  APPLICATION_SENML_EXI = 114,
  /* application/sensml-exi; Ref: [RFC8428] */
  APPLICATION_SENSML_EXI = 115,
  /* application/yang-data+cbor; id=sid; Ref: [RFC9254] */
  APPLICATION_YANG_DATA_CBOR_SID = 140,
  /* application/coap-group+json; Ref: [RFC7390] */
  APPLICATION_COAP_GROUP_JSON = 256,
  /* application/concise-problem-details+cbor; Ref: [RFC9290] */
  APPLICATION_CONCISE_PROBLEM_DETAILS_CBOR = 257,
  /* application/swid+cbor; Ref: [RFC9393] */
  APPLICATION_SWID_CBOR = 258,
  /* application/pkixcmp; Ref: [RFC-ietf-ace-cmpv2-coap-transport-10][RFC4210] */
  APPLICATION_PKIXCMP = 259,
  /* application/dots+cbor; Ref: [RFC9132] */
  APPLICATION_DOTS_CBOR = 271,
  /* application/missing-blocks+cbor-seq; Ref: [RFC9177] */
  APPLICATION_MISSING_BLOCKS_CBOR_SEQ = 272,
  /* application/pkcs7-mime; smime-type=server-generated-key; Ref: [RFC7030][RFC8551][RFC9148] */
  APPLICATION_PKCS7_MIME_SERVER_GENERATED_KEY = 280,
  /* application/pkcs7-mime; smime-type=certs-only; Ref: [RFC8551][RFC9148] */
  APPLICATION_PKCS7_MIME_CERTS_ONLY = 281,
  /* application/pkcs8; Ref: [RFC5958][RFC8551][RFC9148] */
  APPLICATION_PKCS8 = 284,
  /* application/csrattrs; Ref: [RFC7030][RFC9148] */
  APPLICATION_CSRATTRS = 285,
  /* application/pkcs10; Ref: [RFC5967][RFC8551][RFC9148] */
  APPLICATION_PKCS10 = 286,
  /* application/pkix-cert; Ref: [RFC2585][RFC9148] */
  APPLICATION_PKIX_CERT = 287,
  /* application/aif+cbor; Ref: [RFC9237] */
  APPLICATION_AIF_CBOR = 290,
  /* application/aif+json; Ref: [RFC9237] */
  APPLICATION_AIF_JSON = 291,
  /* application/senml+xml; Ref: [RFC8428] */
  APPLICATION_SENML_XML = 310,
  /* application/sensml+xml; Ref: [RFC8428] */
  APPLICATION_SENSML_XML = 311,
  /* application/senml-etch+json; Ref: [RFC8790] */
  APPLICATION_SENML_ETCH_JSON = 320,
  /* application/senml-etch+cbor; Ref: [RFC8790] */
  APPLICATION_SENML_ETCH_CBOR = 322,
  /* application/yang-data+cbor; Ref: [RFC9254] */
  APPLICATION_YANG_DATA_CBOR = 340,
  /* application/yang-data+cbor; id=name; Ref: [RFC9254] */
  APPLICATION_YANG_DATA_CBOR_NAME = 341,
  /* application/td+json; Ref: ["Web of Things (WoT) Thing Description 1.1", April 2022] */
  APPLICATION_TD_JSON = 432,
  /* application/tm+json; Ref: ["Web of Things (WoT) Thing Description 1.1", April 2022] */
  APPLICATION_TM_JSON = 433,
  /* application/voucher-cose+cbor (TEMPORARY - registered 2022-04-12, extension registered 2023-04-04, expires 2024-04-12); Ref: [draft-ietf-anima-constrained-voucher-20] */
  APPLICATION_VOUCHER_COSE_CBOR = 836,
  /* application/vnd.ocf+cbor; Ref: [Michael_Koster] */
  APPLICATION_VND_OCF_CBOR = 10000,
  /* application/oscore; Ref: [RFC8613] */
  APPLICATION_OSCORE = 10001,
  /* application/javascript; Ref: [RFC4329] */
  APPLICATION_JAVASCRIPT = 10002,
  /* application/json; deflate; Ref: [RFC8259][RFC9110, Section 8.4.1.2] */
  APPLICATION_JSON_DEFLATE = 11050,
  /* application/cbor; deflate; Ref: [RFC8949][RFC9110, Section 8.4.1.2] */
  APPLICATION_CBOR_DEFLATE = 11060,
  /* application/vnd.oma.lwm2m+tlv; Ref: [OMA-TS-LightweightM2M-V1_0] */
  APPLICATION_VND_OMA_LWM2M_TLV = 11542,
  /* application/vnd.oma.lwm2m+json; Ref: [OMA-TS-LightweightM2M-V1_0] */
  APPLICATION_VND_OMA_LWM2M_JSON = 11543,
  /* application/vnd.oma.lwm2m+cbor; Ref: [OMA-TS-LightweightM2M-V1_2] */
  APPLICATION_VND_OMA_LWM2M_CBOR = 11544,
  /* text/css; Ref: [RFC2318] */
  TEXT_CSS = 20000,
  /* image/svg+xml; Ref: [https://www.w3.org/TR/SVG/mimereg.html] */
  IMAGE_SVG_XML = 30000
} coap_content_format_t;
