#!/usr/bin/env python3
"""
generate.py — read db/*.rec and emit C header files.

No network access. No heuristics. Deterministic.
"""

import os
import re
import sys
import argparse
import toml

import recfile
import iana_header_utils as utils

script_dir = os.path.dirname(os.path.abspath(__file__))
repo_dir = os.path.dirname(script_dir)
db_dir = os.path.join(repo_dir, 'db')

settings = toml.load(os.path.join(script_dir, 'iana_settings.toml'))
sources = toml.load(os.path.join(repo_dir, 'iana_sources.toml'))


# ---------------------------------------------------------------------------
# Style helpers
# ---------------------------------------------------------------------------

def words_to_screaming_snake(words_str, prefix):
    """'date time string' + 'cbor_tag' -> 'CBOR_TAG_DATE_TIME_STRING'"""
    tokens = words_str.strip().split()
    inner = '_'.join(tokens).upper()
    p = re.sub(r'_{2,}', '_', prefix.upper().rstrip('_') + '_' + inner).strip('_')
    return p


def words_to_pascal(words_str, prefix):
    """'date time string' + 'cbor_tag' -> 'CborTagDateTimeString'"""
    p_tokens = [w.capitalize() for w in prefix.split('_') if w]
    w_tokens = [w.capitalize() for w in words_str.strip().split()]
    return ''.join(p_tokens + w_tokens)


def make_enum_name(words_str, name, tiny_cbor=False):
    if tiny_cbor:
        return words_to_pascal(words_str, name)
    return words_to_screaming_snake(words_str, name)


# ---------------------------------------------------------------------------
# db → c_enum_list / c_macro_list builders
# ---------------------------------------------------------------------------

def load_enum_list(db_file, name, value_parser, tiny_cbor=False):
    """Build c_enum_list dict from a .rec file.

    value_parser(rec) -> (int_key, comment_str) or None to skip
    """
    c_enum_list = {}
    for rec in recfile.read(db_file):
        words = rec.get('Words', '').strip()
        source = rec.get('Source', '').strip()
        if not words or source in ('new', 'needs-manual'):
            print(f"  WARNING: skipping Tag={rec.get('Tag')!r} — no Words (run `make name` then `make check`)", file=sys.stderr)
            continue
        result = value_parser(rec)
        if result is None:
            continue
        int_key, comment = result
        enum_name = make_enum_name(words, name, tiny_cbor=tiny_cbor)
        c_enum_list[int_key] = {"enum_name": enum_name, "comment": comment}
    return c_enum_list


def load_macro_list(db_file, name, value_parser):
    """Build c_macro_list dict for X-macro style registries (HTTP field names)."""
    c_macro_list = {}
    for rec in recfile.read(db_file):
        words = rec.get('Words', '').strip()
        source = rec.get('Source', '').strip()
        if not words or source in ('new', 'needs-manual'):
            print(f"  WARNING: skipping Tag={rec.get('Tag')!r} — no Words", file=sys.stderr)
            continue
        result = value_parser(rec)
        if result is None:
            continue
        macro_name, macro_value, comment = result
        c_macro_list[macro_name] = {"value": macro_value, "comment": comment}
    return c_macro_list


# ---------------------------------------------------------------------------
# Per-registry generators
# ---------------------------------------------------------------------------

def generate_cbor(header_content):
    cbor_cfg = settings['cbor']
    spacing = cbor_cfg.get('spacing_string', '  ')
    tiny_cbor = cbor_cfg.get('style_override', '') == 'tiny_cbor'

    # Simple values
    sv_name = settings['cbor']['simple_value']['name']
    sv_src = sources['iana_cbor_simple_value_source']
    sv_db = os.path.join(db_dir, 'cbor_simple_values.rec')

    def sv_parser(rec):
        try:
            val = int(rec['Tag'])
        except (ValueError, KeyError):
            return None
        sem = rec.get('Semantics', '')
        ref = rec.get('Reference', '')
        comment = '; '.join(filter(None, [sem, f'Ref: {ref}' if ref else '']))
        return val, comment

    sv_enum_list = load_enum_list(sv_db, sv_name, sv_parser, tiny_cbor=tiny_cbor)
    sv_typedef = f"{sv_name}_t"
    sv_comment = spacing + f"/* Autogenerated {sv_src['title']} (Source: {sv_src['source_url']}) */\n"
    sv_ranges = [
        {"start": 0, "end": 19, "description": "Standards Action"},
        {"start": 32, "end": 255, "description": "Specification Required"},
    ]
    header_content = utils.update_c_typedef_enum(
        header_content, sv_typedef, sv_typedef, sv_comment, sv_enum_list,
        sv_ranges, spacing_string=spacing,
    )

    # Tags
    tag_name = settings['cbor']['tag_source']['name']
    tag_src = sources['iana_cbor_tag_source']
    tag_db = os.path.join(db_dir, 'cbor_tags.rec')

    def tag_parser(rec):
        try:
            val = int(rec['Tag'])
        except (ValueError, KeyError):
            return None
        sem = rec.get('Semantics', '')
        ref = rec.get('Reference', '')
        comment = '; '.join(filter(None, [sem, f'Ref: {ref}' if ref else '']))
        return val, comment

    tag_enum_list = load_enum_list(tag_db, tag_name, tag_parser, tiny_cbor=tiny_cbor)
    tag_typedef = f"{tag_name}_t"
    tag_comment = spacing + f"/* Autogenerated {tag_src['title']} (Source: {tag_src['source_url']}) */\n"
    header_content = utils.update_c_typedef_enum(
        header_content, tag_typedef, tag_typedef, tag_comment, tag_enum_list,
        spacing_string=spacing, int_suffix='ULL',
    )

    return header_content


def generate_coap(header_content):
    coap_cfg = settings['coap']
    spacing = coap_cfg.get('spacing_string', '  ')
    src_rr = sources['iana_coap_request_response_source']

    def coap_code_parser(rec):
        code_str = rec.get('Tag', '').strip()
        # Convert dot-notation "0.01" -> integer (class * 32 + detail)
        if '.' in code_str:
            try:
                cls, detail = code_str.split('.')
                val = int(cls) * 32 + int(detail)
            except ValueError:
                return None
        else:
            try:
                val = int(code_str)
            except ValueError:
                return None
        sem = rec.get('Semantics', '')
        ref = rec.get('Reference', '')
        comment = '; '.join(filter(None, [sem, f'Ref: {ref}' if ref else '']))
        return val, comment

    code_name = settings['coap']['request_response']['name']
    code_typedef = f"{code_name}_t"
    code_comment = spacing + f"/* Autogenerated {src_rr['title']} */\n"

    # Merge request + response + signaling codes into one enum
    combined = {}
    for kind in ('request', 'response', 'signaling'):
        db_file = os.path.join(db_dir, f'coap_{kind}_codes.rec')
        if os.path.exists(db_file):
            combined.update(load_enum_list(db_file, code_name, coap_code_parser))

    coap_ranges = [
        {"start": 0,   "end": 31,  "description": "Requests (0.xx)"},
        {"start": 32,  "end": 95,  "description": "Success (2.xx)"},
        {"start": 160, "end": 191, "description": "Client Error (4.xx)"},
        {"start": 192, "end": 223, "description": "Server Error (5.xx)"},
        {"start": 224, "end": 255, "description": "Signaling (7.xx)"},
    ]
    header_content = utils.update_c_typedef_enum(
        header_content, code_typedef, code_typedef, code_comment, combined,
        coap_ranges, spacing_string=spacing,
    )

    # Options
    opt_name = settings['coap']['option']['name']
    opt_src = sources['iana_coap_option_source']
    opt_db = os.path.join(db_dir, 'coap_options.rec')

    def opt_parser(rec):
        try:
            val = int(rec['Tag'])
        except (ValueError, KeyError):
            return None
        sem = rec.get('Semantics', '')
        ref = rec.get('Reference', '')
        comment = '; '.join(filter(None, [sem, f'Ref: {ref}' if ref else '']))
        return val, comment

    opt_enum_list = load_enum_list(opt_db, opt_name, opt_parser)
    opt_typedef = f"{opt_name}_t"
    opt_comment = spacing + f"/* Autogenerated {opt_src['title']} (Source: {opt_src.get('source', '')}) */\n"
    header_content = utils.update_c_typedef_enum(
        header_content, opt_typedef, opt_typedef, opt_comment, opt_enum_list,
        spacing_string=spacing,
    )

    # Content formats
    cf_name = settings['coap']['content_format']['name']
    cf_src = sources['iana_coap_content_format_source']
    cf_db = os.path.join(db_dir, 'coap_content_formats.rec')

    def cf_parser(rec):
        try:
            val = int(rec['Tag'])
        except (ValueError, KeyError):
            return None
        sem = rec.get('Semantics', '')
        ref = rec.get('Reference', '')
        comment = '; '.join(filter(None, [sem, f'Ref: {ref}' if ref else '']))
        return val, comment

    cf_enum_list = load_enum_list(cf_db, cf_name, cf_parser)
    cf_typedef = f"{cf_name}_t"
    cf_comment = spacing + f"/* Autogenerated {cf_src['title']} (Source: {cf_src.get('source', '')}) */\n"
    header_content = utils.update_c_typedef_enum(
        header_content, cf_typedef, cf_typedef, cf_comment, cf_enum_list,
        spacing_string=spacing,
    )

    return header_content


def generate_http(header_content):
    http_cfg = settings['http']
    spacing = http_cfg.get('spacing_string', '  ')

    # Status codes — note: settings has a typo ([coap.http_status_code] instead of [http.*])
    # We read from whichever section exists
    sc_section = settings.get('http', {}).get('http_status_code') or settings.get('coap', {}).get('http_status_code', {})
    sc_name = sc_section.get('name', 'http_status_code')
    sc_src = sources['iana_http_status_code_source']
    sc_db = os.path.join(db_dir, 'http_status_codes.rec')

    def sc_parser(rec):
        try:
            val = int(rec['Tag'])
        except (ValueError, KeyError):
            return None
        sem = rec.get('Semantics', '')
        ref = rec.get('Reference', '')
        comment = '; '.join(filter(None, [sem, f'Ref: {ref}' if ref else '']))
        return val, comment

    sc_enum_list = load_enum_list(sc_db, sc_name, sc_parser)
    sc_typedef = f"{sc_name}_t"
    sc_comment = spacing + f"/* Autogenerated {sc_src['title']} (Source: {sc_src['source_url']}) */\n"
    sc_ranges = [
        {"start": 100, "end": 199, "description": "Informational - Request received, continuing process"},
        {"start": 200, "end": 299, "description": "Success - The action was successfully received, understood, and accepted"},
        {"start": 300, "end": 399, "description": "Redirection - Further action must be taken in order to complete the request"},
        {"start": 400, "end": 499, "description": "Client Error - The request contains bad syntax or cannot be fulfilled"},
        {"start": 500, "end": 599, "description": "Server Error - The server failed to fulfill an apparently valid request"},
    ]
    header_content = utils.update_c_typedef_enum(
        header_content, sc_typedef, sc_typedef, sc_comment, sc_enum_list,
        sc_ranges, spacing_string=spacing,
    )

    # Field names (X-macro)
    fn_section = settings.get('http', {}).get('http_field_name') or settings.get('coap', {}).get('http_field_name', {})
    fn_name = fn_section.get('name', 'http_field_name')
    fn_src = sources['iana_http_field_name_source']
    fn_db = os.path.join(db_dir, 'http_field_names.rec')

    def fn_macro_name(rec):
        words = rec.get('Words', '').strip()
        return words_to_screaming_snake(words, fn_name)

    c_macro_list = {}
    for rec in recfile.read(fn_db):
        words = rec.get('Words', '').strip()
        source = rec.get('Source', '').strip()
        if not words or source in ('new', 'needs-manual'):
            continue
        tag = rec.get('Tag', '')  # field name string e.g. "Content-Type"
        sem = rec.get('Semantics', '')
        ref = rec.get('Reference', '')
        comment = '; '.join(filter(None, [tag, sem, f'Ref: {ref}' if ref else '']))
        macro_name = words_to_screaming_snake(words, fn_name)
        c_macro_list[macro_name] = {"value": f'"{tag}"', "comment": comment}

    fn_comment = f"/* Autogenerated {fn_src['title']} (Source: {fn_src['source_url']}) */\n"
    header_content = utils.update_c_const_macro(header_content, fn_name, fn_comment, c_macro_list)

    return header_content


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description='Generate C headers from db/*.rec')
    parser.add_argument('--settings', default=os.path.join(script_dir, 'iana_settings.toml'))
    args = parser.parse_args()

    if not os.path.isdir(db_dir):
        print(f"ERROR: db/ not found. Run `make sync` and `make name` first.", file=sys.stderr)
        sys.exit(1)

    cbor_out = os.path.join(script_dir, settings['cbor']['generated_header_filepath'])
    coap_out = os.path.join(script_dir, settings['coap']['generated_header_filepath'])
    http_out = os.path.join(script_dir, settings['http']['generated_header_filepath'])

    for path in (cbor_out, coap_out, http_out):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        if not os.path.exists(path):
            open(path, 'w').close()

    def _load(path):
        with open(path, 'r', encoding='utf-8') as f:
            return f.read()

    def _save(path, content):
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)

    print("Generating cbor_constants.h ...")
    _save(cbor_out, generate_cbor(_load(cbor_out)))

    print("Generating coap_constants.h ...")
    _save(coap_out, generate_coap(_load(coap_out)))

    print("Generating http_constants.h ...")
    _save(http_out, generate_http(_load(http_out)))

    print("Done.")


if __name__ == '__main__':
    main()
